/**
 * RootLayout Component
 * The main layout wrapper for the entire Next.js application.
 * Configures fonts, metadata, and global providers.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Global site metadata metadata.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { MenuProvider } from "./context/MenuContext";
import { ModalProvider } from "./context/ModalContext";
import { UserProvider } from "./context/UserContext";

/**
 * Root component that provides the HTML structure and wraps children in global providers.
 *
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - The page content.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col h-full w-full overflow-hidden">
        <UserProvider>
          <ModalProvider>
            <MenuProvider>
              {children}
            </MenuProvider>
          </ModalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
